# Generated by Django 3.2.4 on 2021-06-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('is_main', models.BooleanField(verbose_name='Endereço Principal?')),
            ],
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='client_address')),
            ],
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('birthdate', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='user_address')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='user_client')),
            ],
            bases=('core.base',),
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='address_user'),
        ),
    ]
