# Generated by Django 3.2.4 on 2021-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210627_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='local',
            field=models.CharField(default='', max_length=255, verbose_name='Local'),
        ),
    ]
