# Generated by Django 3.2.4 on 2021-06-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
