# Generated by Django 3.2.4 on 2021-06-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210627_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
