# Generated by Django 3.2.4 on 2021-06-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_base_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address_id',
        ),
    ]
