# Generated by Django 3.2.4 on 2021-06-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_client_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_client',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
        ),
    ]
