# Generated by Django 3.2.4 on 2021-06-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
    ]
